apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  annotations:
    github.com/project-slug: alec-malcolm/demo
  tags:
    - devops
    - docker
    - api
  links:
    - title: Some link
      url: https://google.ca
spec:
  type: openapi
  lifecycle: experimental
  owner: camis-developers
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Demo API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...